[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify-functions"

[dev]
  command = "vite" # comando para iniciar Vite en modo de desarrollo
  port = 3000 # puerto por defecto de Vite
  publish = "dist"


